In [1]:
from pprint import pprint
from copy import deepcopy

import pandas as pd

from riot_apis import RiotAPI

pd.set_option("display.max_columns", None)

In [2]:
riot_api = RiotAPI()

In [3]:
summoners = pd.read_csv("./csv/solo_rank/summoners.csv")
summoners

,id,accountId,puuid,name,profileIconId,revisionDate,summonerLevel,player
0,yWX9RJDAkRrpjPQ_Bkk-BKNWdOtMMjnurhvg68ERTwEwgg,quJJnwe4aCTGsuaXotjA5bdQNa7uu9G7WtgolS5AlFJ-,Fs50-pGDKSsKlb5zGX8e0jK6GqklP-t5WYXxtDTSYp1H_o...,Hide on bush,6,1688239916647,673,Faker
1,NWNsfGC4nque7EhL5lQURPp3DLJFgTbABZPzZMl4LE-DB04,z1zx33nGnaij-eawMocYUvhLXTzye9KBVnAB0hGdv8YsQUc,pk7rN4ofWK5ELk3pHUpacjaigU4I6fbX6mKPHM1UgC4_z2...,T1 Gumayusi,7,1687586570000,610,Gumayusi
2,0vdfK7W3R5Jwk2HihJHmC7Hb_LCuHfrJ6oAMguw8levBryg,1q81H0yAkqS3eu0ZUGnmFnjaKNpYzGuLfKPdyYHe8kmizwk,1vX6Mtg79L10LDUcV2b9mx5AqQ5xVwSMBXLDQG-EIL6a5s...,sprtkim,5870,1689048836941,545,Zeus
3,KEWKloLZADChqraN56rgbQolZm5YkGmRG09GDICj2kk8-oo,AHlph6IWSgAuL48HuqKhKwZ3OK5jUgV2YA6dAHdTlJ_dUq...,cei1aC8vNtl1ULpjPDJdh4BUiiB1rcD9yOSZh4ZL0phP83...,우 제,4787,1687887271000,147,Zeus
4,MD7jjLTBWDkCLBoeQgzgtlTrCf82fGIsObwauXilwjFsxP...,2TQBlpQ6MLIVKrX2ZWpB4hKjQXvNtrkH7Q96gwDV7A-HL7...,ikHzLhp-twwSdPgn_71NzVgrsyHH15K017klRkNWOZCBRQ...,T1 Oner,1425,1685698948000,85,Oner
5,wfaDxYA1xxNWHhtSouLBS2-gqinWbEa-_h2-a_ccwpdQS_U,Q1OwNyNY6M3q8aexXMWFvR4GwbUJNcT9_0Xlu_GVgZ-6A8s,bYMd6o-rtBKbGvhw0wv-xxyaHRnm56V0nORbDFwOBi5Jb_...,역천괴,20,1689007552421,788,Keria
6,q1lzCYqf7dx6_-9rrRD_JUl2uVRlk0NKMp7_25Ftv2t3Zp...,QcJDq_r1H53hIvBqt9ky-058hPkPL_kDI_89iVadLT_4tk...,4_QO1dczTj1fYijPQB7IU-wOPqdTeO6JAqZ5si7DT3PLWF...,ABC도레미,29,1688133085000,42,Keria
7,tDrcFDKg2XWy_9nYkAUTo2xcVqKi1klKUJ5-mQ2DU2gxjm...,HSo78a2cU5ZwK2X20s-yUymihmHB3_iySP-NTP-dN1TTFM...,25E8BukJiTePKfgwa1d4eH-oSnq91AaBIki5P4eRiYChkw...,최애의 구마유시,3,1689009105461,60,Gumayusi
8,yFs22vLrSlgBk_RZuwGFLLAVBNeT4oK-6xqI3pYH_wd06Eg,q-nJukjWv5EuvG8-WKew9nYgH7RfMYgeHPG7_kBB_AR7utk,mqPzspJfp5h7C733PnAy3dSSjhUoYJP3Fs0-L7XpfK_NeC...,가던 길이나 가,1162,1689067265077,448,Oner

In [5]:
participants = pd.read_csv("./csv/solo_rank/participants.csv")
participants

,allInPings,assistMePings,assists,baitPings,baronKills,basicPings,bountyLevel,champExperience,champLevel,championId,championName,championTransform,commandPings,consumablesPurchased,damageDealtToBuildings,damageDealtToObjectives,damageDealtToTurrets,damageSelfMitigated,dangerPings,deaths,detectorWardsPlaced,doubleKills,dragonKills,eligibleForProgression,enemyMissingPings,enemyVisionPings,firstBloodAssist,firstBloodKill,firstTowerAssist,firstTowerKill,gameEndedInEarlySurrender,gameEndedInSurrender,getBackPings,goldEarned,goldSpent,holdPings,individualPosition,inhibitorKills,inhibitorTakedowns,inhibitorsLost,item0,item1,item2,item3,item4,item5,item6,itemsPurchased,killingSprees,kills,lane,largestCriticalStrike,largestKillingSpree,largestMultiKill,longestTimeSpentLiving,magicDamageDealt,magicDamageDealtToChampions,magicDamageTaken,needVisionPings,neutralMinionsKilled,nexusKills,nexusLost,nexusTakedowns,objectivesStolen,objectivesStolenAssists,onMyWayPings,participantId,pentaKills,physicalDamageDealt,physicalDamageDealtToChampions,physicalDamageTaken,playerAugment1,playerAugment2,playerAugment3,playerAugment4,playerSubteamId,profileIcon,pushPings,puuid,quadraKills,riotIdName,riotIdTagline,role,sightWardsBoughtInGame,spell1Casts,spell2Casts,spell3Casts,spell4Casts,subteamPlacement,summoner1Casts,summoner1Id,summoner2Casts,summoner2Id,summonerId,summonerLevel,summonerName,teamEarlySurrendered,teamId,teamPosition,timeCCingOthers,timePlayed,totalAllyJungleMinionsKilled,totalDamageDealt,totalDamageDealtToChampions,totalDamageShieldedOnTeammates,totalDamageTaken,totalEnemyJungleMinionsKilled,totalHeal,totalHealsOnTeammates,totalMinionsKilled,totalTimeCCDealt,totalTimeSpentDead,totalUnitsHealed,tripleKills,trueDamageDealt,trueDamageDealtToChampions,trueDamageTaken,turretKills,turretTakedowns,turretsLost,unrealKills,visionClearedPings,visionScore,visionWardsBoughtInGame,wardsKilled,wardsPlaced,win,matchId
0,0.0,0.0,2,0.0,0,0.0,0,11435,13,58,Renekton,0,2.0,3,821,3226,821,47398,0.0,9,2,0,0,True,2.0,6.0,False,False,False,False,False,False,2.0,10070,8850,0.0,TOP,0,0,2,3143,6630,2421,0,3047,1054,3364,17,1,5,JUNGLE,0,2,1,346,7462,2757,11252,1.0,11,0,1,0,0,0,3.0,1,0,104042,11854,29064,0.0,0.0,0.0,0.0,0.0,27,0.0,zQBZKwU3jcRKIGDO64sy-UcnoZs6gMIOM3ZTuRr5gF_So7...,0,NaN,NaN,NONE,0,80,30,76,10,0.0,2,12,4,4,0XXBneTtEPm8c5Q1hXsYT32hQkLQz8ESgDPV6ewTGvJPHG...,108,미니언14,False,100,TOP,19,1528,8.0,111763,14689,0,42473,0.0,9628,0,174,49,235,1,0,258,78,2157,0,1,11,0,0.0,21,2,5,7,False,KR_6562408455
1,0.0,0.0,7,0.0,0,0.0,1,11058,13,62,MonkeyKing,0,8.0,7,1653,2346,1653,21102,0.0,5,5,0,0,True,6.0,9.0,False,False,False,False,False,False,8.0,10376,10125,0.0,JUNGLE,0,0,2,1037,6632,2055,3071,3047,3133,3364,24,2,8,JUNGLE,0,2,1,630,11598,2355,12058,0.0,91,0,1,0,0,0,43.0,2,0,66400,18451,18760,0.0,0.0,0.0,0.0,0.0,5378,0.0,FJvfOmSn_-kwkg0qCUYkKi_gRglvPbJYTFcqIzDXpDGOvT...,0,NaN,NaN,NONE,0,112,41,66,16,0.0,17,11,5,4,XnliaNI_imnReR_iBw9_TQVWdfGI577aFOE3JiKo76z8E38,706,카니발 갱,False,100,JUNGLE,19,1528,62.0,100427,21953,0,31657,15.0,10745,0,15,192,157,1,0,22427,1146,838,1,1,11,0,0.0,27,6,5,7,False,KR_6562408455
2,0.0,1.0,6,0.0,0,0.0,0,10548,13,163,Taliyah,0,12.0,2,0,0,0,13069,0.0,9,0,0,0,True,0.0,5.0,False,True,False,False,False,False,4.0,8448,7985,0.0,MIDDLE,0,0,2,2424,1056,4644,3111,3040,1052,3364,17,0,2,MIDDLE,0,0,1,363,84363,11456,6163,0.0,14,0,1,0,0,0,8.0,3,0,8944,1120,14987,0.0,0.0,0.0,0.0,0.0,3838,0.0,_Yed9oI0Dl0gbRWKBt0ndnXIXROwoJodshrCkkgfk8rl2W...,0,NaN,NaN,SOLO,0,161,43,80,22,0.0,3,4,8,12,Tl0b_LlaZub67H3QDmKrHZAjgEmGp9EnxYrfNx2fEbXdqFk,1021,BRO Ivory,False,100,MIDDLE,29,1528,6.0,96052,12826,0,22241,0.0,886,0,141,553,288,1,0,2745,250,1091,0,0,11,0,0.0,14,0,2,5,False,KR_6562408455
3,0.0,0.0,2,0.0,0,0.0,0,9366,12,145,Kaisa,0,4.0,6,6553,6553,6553,11689,0.0,7,5,2,0,True,0.0,0.0,False,False,False,False,False,False,6.0,11144,10100,0.0,BOTTOM,0,0,2,1037,6677,1055,3087,3115,3006,3363,22,3,7,BOTTOM,279,2,2,405,58108,10443,4567,0.0,0,0,1,0,0,0,7.0,4,0,55507,9924,13411,0.0,0.0,0.0,0.0,0.0,3614,0.0,-0j5gHU8XcF6ajmfRjEl91o0AjwgKVZBHuf2cmrr3wkFVb...,0,NaN,NaN,CARRY,0,57,31,50,5,0.0,5,1,4,4,u7UB9yfNFJGliFUZ6hzOVPGJsoJf4zQt6cj8dPxXQe8U4lk,756,숟인데요,False,100,BOTTOM,1,1528,0.0,113782,20435,0,18442,0.0,2194,0,179,16,185,1,0,166,67,462,2,2,11,0,0.0,25,5,6,13,False,KR_6562408455
4,1.0,0.0,11,0.0,0,0.0,0,7671,11,89,Leona,0,7.0,14,129,129,129,32344,0.0,7,9,0,0,True,0.0,6.0,False,False,False,False,False,False,4.0,6187,5850,0.0,UTILITY,0,0,2,3001,3857,2055,3023,3047,0,3364,28,0,0,BOTTOM,0,0,0,678,5688,3091,6256,0.0,0,0,1,0,0,0,12.0,5,0,5584,2018,17433,0.0,0.0,0.0,0.0,0.0,4856,0.0,bYMd6o-rtBKbGvhw0wv-xxyaHRnm56V0nORbDFwOBi5Jb_...,0,NaN,NaN,SUPPORT,0,44,30,36,10,0.0,6,14,21,4,wfaDxYA1xxNWHhtSouLBS2-gqinWbEa-_h2-a_ccwpdQS_U,783,역천괴,False,100,UTILITY,60,1528,0.0,18090,5872,0,24629,0.0,563,0,32,210,175,1,0,6816,762,939,0,0,11,0,1.0,64,10,7,38,False,KR_6562408455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9107,0.0,0.0,6,0.0,0,0.0,0,17436,17,133,Quinn,0,2.0,7,7563,12820,7563,14338,0.0,7,7,1,0,True,18.0,6.0,False,False,False,False,False,False,7.0,14686,12075,0.0,TOP,0,0,0,3006,1053,0,3087,3091,3124,3340,28,1,4,TOP,470,3,2,527,86599,7985,9892,0.0,19,0,0,1,0,0,0.0,6,0,133098,16296,10867,0.0,0.0,0.0,0.0,0.0,5629,0.0,ljGxTHqPLTE1MrIl_YF6SgUpnm4l2Y4WTbP7YpzE0SA1EY...,0,NaN,NaN,SOLO,0,62,26,19,47,0.0,4,14,4,4,04LKscCY5QkK9pka1WOfeqQ_QjapaCrcb0F1VUH-C1j9I-...,177,살퀸레,False,200,TOP,27,1848,6.0,220612,25195,0,22394,7.0,5005,0,252,127,240,1,0,914,914,1634,3,5,4,0,0.0,33,7,3,17,True,KR_6586262754
9108,0.0,18.0,6,0.0,2,0.0,0,13201,15,57,Maokai,0,24.0,10,50,15729,50,25026,0.0,3,8,0,1,True,16.0,11.0,False,False,True,False,False,False,16.0,12435,11775,3.0,JUNGLE,0,0,0,2055,4637,3165,3158,6667,1058,3364,25,1,3,JUNGLE,0,2,1,848,154284,16635,14737,0.0,161,0,0,0,1,0,33.0,7,0,20084,1097,18262,0.0,0.0,0.0,0.0,0.0,4568,1.0,dXHCrKyYUokQgrkHoXUUmnUULq5bgA6EjVi42x7JK7W3-s...,0,NaN,NaN,NONE,0,144,54,111,11,0.0,5,4,20,11,lGcwqIgLgrWuP1juQwvfblbHaZU9Jg2pTHrL1cV-tPxW6ZU,562,2 C U Again,False,200,JUNGLE,66,1848,104.0,230160,20838,0,33325,31.0,21542,1481,23,693,87,5,0,55792,3106,324,0,1,4,0,0.0,47,9,11,11,True,KR_6586262754
9109,1.0,26.0,6,0.0,0,0.0,2,17564,17,18,Tristana,0,27.0,3,18722,32777,18722,17591,0.0,5,2,0,0,True,23.0,20.0,False,False,False,True,False,False,17.0,16724,14880,0.0,MIDDLE,1,1,0,0,3072,3111,6675,6672,3036,3363,30,3,7,MIDDLE,675,2,1,611,37006,2288,15592,0.0,33,1,0,1,0,0,47.0,8,0,248634,22605,7914,0.0,0.0,0.0,0.0,0.0,2076,0.0,yqkUpz3oKn9ftBHialPY7uEoPX8so9_zPKtdy9j9zB5gEM...,0,NaN,NaN,SOLO,0,75,51,77,8,0.0,5,12,4,4,yjnu0gy9k8k7Hfu9mFKEotsLBu8PMvnnfxsxC810UMPqHJ...,439,DK Saint,False,200,MIDDLE,6,1848,19.0,285641,24894,0,23935,7.0,5803,0,249,50,174,1,0,0,0,428,6,6,4,0,0.0,39,2,7,12,True,KR_6586262754
9110,0.0,5.0,7,0.0,0,0.0,2,15771,16,81,Ezreal,0,4.0,5,1070,20022,1070,7048,0.0,2,3,0,0,True,10.0,7.0,False,False,False,False,False,False,6.0,12896,10208,0.0,BOTTOM,0,0,0,1055,3078,3042,3133,3035,3158,3363,22,1,3,BOTTOM,0,2,1,771,18633,6220,5551,0.0,8,0,0,1,0,0,8.0,9,0,157079,20009,7982,0.0,0.0,0.0,0.0,0.0,1644,0.0,2E91m-VDv48Ops_LuAz3q0wtqPecWlzPJ8Qj3vK41yDfrK...,0,NaN,NaN,CARRY,0,338,56,46,12,0.0,5,7,4,4,WiJA3hoR8Czx4ZCvbXC5nJoHLHrh291weBPU-4J9K46bnGA,194,광주충장파,False,200,BOTTOM,7,1848,4.0,183975,27002,0,13815,4.0,6667,862,256,109,42,4,0,8261,771,282,0,2,4,0,0.0,29,3,7,10,True,KR_6586262754
9111,1.0,1.0,11,0.0,0,0.0,0,9826,12,497,Rakan,0,50.0,13,202,722,202,17019,0.0,7,8,0,0,True,12.0,0.0,False,False,True,False,False,False,16.0,8144,7900,0.0,UTILITY,0,0,0,3860,3107,2065,4638,3111,0,3364,29,0,0,BOTTOM,0,0,0,318,9310,5802,8633,0.0,0,0,0,0,0,0,80.0,10,0,5488,817,11062,0.0,0.0,0.0,0.0,0.0,2076,1.0,NX7_LLFy6t20cX7W4Tknl_aJkx2d8akqGyRzZLkAakVknE...,0,NaN,NaN,SUPPORT,0,49,58,93,6,0.0,5,14,5,4,Vj4rrPFSYS521Le5C7b4eaGJlfnnx4OM-CkEl_AhjG_89F...,138,Dhorreur,False,200,UTILITY,44,1848,0.0,24998,8850,2490,20331,0.0,5064,1845,44,168,173,4,0,10199,2230,636,0,2,4,0,0.0,112,8,15,62,True,KR_6586262754

In [6]:
info = pd.read_csv('./csv/solo_rank/info.csv')
info

,gameCreation,gameDuration,gameEndTimestamp,gameId,gameMode,gameName,gameStartTimestamp,gameType,gameVersion,mapId,platformId,queueId,tournamentCode,matchId
0,1687790704264,1528,1687792258390,6562408455,CLASSIC,teambuilder-match-6562408455,1687790729794,MATCHED_GAME,13.12.515.4234,11,KR,420,NaN,KR_6562408455
1,1687101184872,1643,1687102906655,6549404662,CLASSIC,teambuilder-match-6549404662,1687101263299,MATCHED_GAME,13.12.515.4234,11,KR,420,NaN,KR_6549404662
2,1685975478803,1412,1685976919169,6529671893,CLASSIC,teambuilder-match-6529671893,1685975506594,MATCHED_GAME,13.11.512.8126,11,KR,420,NaN,KR_6529671893
3,1686063356442,2045,1686065429963,6531647247,CLASSIC,teambuilder-match-6531647247,1686063384609,MATCHED_GAME,13.11.512.9046,11,KR,420,NaN,KR_6531647247
4,1688023305313,939,1688024256080,6566186414,CLASSIC,teambuilder-match-6566186414,1688023317008,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6566186414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908,1689001772902,1250,1689003033022,6586580378,CLASSIC,teambuilder-match-6586580378,1689001782245,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6586580378
909,1689002783508,1311,1689004112853,6586605911,CLASSIC,teambuilder-match-6586605911,1689002801212,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6586605911
910,1689000808680,924,1689001742249,6586550631,CLASSIC,teambuilder-match-6586550631,1689000818346,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6586550631
911,1689005954650,918,1689006881246,6586679840,CLASSIC,teambuilder-match-6586679840,1689005962971,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6586679840
912,1688993134117,1848,1688994996780,6586262754,CLASSIC,teambuilder-match-6586262754,1688993148010,MATCHED_GAME,13.13.518.539,11,KR,420,NaN,KR_6586262754

In [7]:
stats = pd.read_csv(
    "./csv/solo_rank/stats.csv", index_col=["player", "teamPosition"]
)
stats

                       championName  games  win  loss   winrate      kills
player   teamPosition
Gumayusi BOTTOM              Draven      3    2     1  0.666667  14.000000  \
         BOTTOM              Ezreal      2    1     1  0.500000  11.000000
         BOTTOM               Kaisa      4    2     2  0.500000   4.500000
         BOTTOM              Lucian      1    1     0  1.000000   6.000000
         BOTTOM         MissFortune      3    2     1  0.666667  14.333333
         BOTTOM               Nilah      1    1     0  1.000000   3.000000
         BOTTOM               Vayne      3    2     1  0.666667   9.333333
         BOTTOM               Xayah      1    1     0  1.000000  16.000000
         JUNGLE             Belveth      1    0     1  0.000000   7.000000
         JUNGLE                Rell      1    1     0  1.000000   5.000000
Keria    BOTTOM              Ezreal      1    1     0  1.000000   6.000000
         TOP                  Fiora      1    1     0  1.000000   3.000000
         TOP              Gangplank      1    0     1  0.000000   3.000000
         TOP                 Gragas      1    0     1  0.000000   6.000000
         UTILITY            Alistar      2    1     1  0.500000   1.000000
         UTILITY             Gragas      1    1     0  1.000000   2.000000
         UTILITY       Heimerdinger      1    1     0  1.000000   2.000000
         UTILITY              Karma      1    0     1  0.000000   4.000000
         UTILITY           Nautilus      4    4     0  1.000000   1.750000
         UTILITY              Rakan      1    0     1  0.000000   0.000000
         UTILITY              Viego      1    0     1  0.000000   3.000000
Oner     BOTTOM              Samira      1    0     1  0.000000   5.000000
         BOTTOM               Vayne      1    1     0  1.000000  12.000000
         BOTTOM               Xayah      2    1     1  0.500000   3.500000
         JUNGLE             Belveth      4    3     1  0.750000   7.750000
         JUNGLE              LeeSin      2    1     1  0.500000   8.000000
         JUNGLE               Sylas      1    0     1  0.000000   5.000000
         JUNGLE               Viego      2    0     2  0.000000   9.500000
Zeus     BOTTOM            Aphelios      1    0     1  0.000000   0.000000
         BOTTOM              Ezreal      1    0     1  0.000000   1.000000
         BOTTOM               Kaisa      1    0     1  0.000000   4.000000
         BOTTOM               Xayah      1    1     0  1.000000  10.000000
         MIDDLE                 Jax      1    1     0  1.000000  14.000000
         TOP              Gangplank      2    2     0  1.000000   4.000000
         TOP                    Jax      4    2     2  0.500000   3.250000
         TOP                 Lucian      1    1     0  1.000000   5.000000
         TOP                   Ornn      1    0     1  0.000000   1.000000
         TOP               Renekton      2    1     1  0.500000   6.000000
         TOP                 Rumble      1    1     0  1.000000   4.000000

                          deaths    assists       kda
player   teamPosition
Gumayusi BOTTOM         5.000000   5.000000  3.800000
         BOTTOM         4.500000   6.000000  3.777778
         BOTTOM         1.750000   1.750000  3.571429
         BOTTOM         6.000000   9.000000  2.500000
         BOTTOM         5.000000   3.000000  3.466667
         BOTTOM         4.000000   6.000000  2.250000
         BOTTOM         5.333333   6.333333  2.937500
         BOTTOM         3.000000   8.000000  8.000000
         JUNGLE        10.000000  15.000000  2.200000
         JUNGLE         5.000000  17.000000  4.400000
Keria    BOTTOM         5.000000   8.000000  2.800000
         TOP            6.000000   4.000000  1.166667
         TOP           11.000000   8.000000  1.000000
         TOP            6.000000   5.000000  1.833333
         UTILITY        7.500000  13.500000  1.933333
         UTILITY        5.000000  14.000000  3.200000
         UTILITY        6.000000  14.000000  2.666667
         UTILITY        7.000000   8.000000  1.714286
         UTILITY        4.250000  16.750000  4.352941
         UTILITY        8.000000  17.000000  2.125000
         UTILITY        7.000000   2.000000  0.714286
Oner     BOTTOM         3.000000   1.000000  2.000000
         BOTTOM         5.000000   9.000000  4.200000
         BOTTOM         6.000000  11.000000  2.416667
         JUNGLE         4.250000   8.500000  3.823529
         JUNGLE         4.500000   5.500000  3.000000
         JUNGLE        12.000000   3.000000  0.666667
         JUNGLE         7.000000  10.500000  2.857143
Zeus     BOTTOM         9.000000   0.000000  0.000000
         BOTTOM         5.000000   1.000000  0.400000
         BOTTOM         5.000000   1.000000  1.000000
         BOTTOM         4.000000   8.000000  4.500000
         MIDDLE         3.000000   5.000000  6.333333
         TOP            5.000000   5.000000  1.800000
         TOP            5.250000   3.500000  1.285714
         TOP            5.000000   6.000000  2.200000
         TOP            3.000000   0.000000  0.333333
         TOP            5.500000   3.500000  1.727273
         TOP            3.000000   4.000000  2.666667

In [14]:
if 'Zeus' in stats.index.get_level_values('player'):
    zeus_stats = stats.loc["Zeus"].reset_index().sort_values(
        ["teamPosition", "games", "winrate"], ascending=False
    )
else:
    zeus_stats = pd.DataFrame()
zeus_stats

,teamPosition,championName,games,win,loss,winrate,kills,deaths,assists,kda
6,TOP,Jax,4,2,2,0.5,3.25,5.25,3.5,1.285714
5,TOP,Gangplank,2,2,0,1.0,4.00,5.00,5.0,1.800000
9,TOP,Renekton,2,1,1,0.5,6.00,5.50,3.5,1.727273
7,TOP,Lucian,1,1,0,1.0,5.00,5.00,6.0,2.200000
10,TOP,Rumble,1,1,0,1.0,4.00,3.00,4.0,2.666667
8,TOP,Ornn,1,0,1,0.0,1.00,3.00,0.0,0.333333
4,MIDDLE,Jax,1,1,0,1.0,14.00,3.00,5.0,6.333333
3,BOTTOM,Xayah,1,1,0,1.0,10.00,4.00,8.0,4.500000
0,BOTTOM,Aphelios,1,0,1,0.0,0.00,9.00,0.0,0.000000
1,BOTTOM,Ezreal,1,0,1,0.0,1.00,5.00,1.0,0.400000
2,BOTTOM,Kaisa,1,0,1,0.0,4.00,5.00,1.0,1.000000

In [16]:
if 'Oner' in stats.index.get_level_values('player'):
    oner_stats = stats.loc["Oner"].reset_index().sort_values(
        ["teamPosition", "games", "winrate"], ascending=False
    )
else:
    oner_stats = pd.DataFrame()
oner_stats

,teamPosition,championName,games,win,loss,winrate,kills,deaths,assists,kda
3,JUNGLE,Belveth,4,3,1,0.75,7.75,4.25,8.5,3.823529
4,JUNGLE,LeeSin,2,1,1,0.50,8.00,4.50,5.5,3.000000
6,JUNGLE,Viego,2,0,2,0.00,9.50,7.00,10.5,2.857143
5,JUNGLE,Sylas,1,0,1,0.00,5.00,12.00,3.0,0.666667
2,BOTTOM,Xayah,2,1,1,0.50,3.50,6.00,11.0,2.416667
1,BOTTOM,Vayne,1,1,0,1.00,12.00,5.00,9.0,4.200000
0,BOTTOM,Samira,1,0,1,0.00,5.00,3.00,1.0,2.000000

In [17]:
if 'Faker' in stats.index.get_level_values('player'):
    faker_stats = stats.loc["Faker"].reset_index().sort_values(
        ["teamPosition", "games", "winrate"], ascending=False
    )
else:
    faker_stats = pd.DataFrame()
faker_stats

Empty DataFrame
Columns: []
Index: []

In [18]:
if 'Gumayusi' in stats.index.get_level_values('player'):
    gumayusi_stats = stats.loc["Gumayusi"].reset_index().sort_values(
        ["teamPosition", "games", "winrate"], ascending=False
    )
else:
    gumayusi_stats = pd.DataFrame()
gumayusi_stats

,teamPosition,championName,games,win,loss,winrate,kills,deaths,assists,kda
9,JUNGLE,Rell,1,1,0,1.000000,5.000000,5.000000,17.000000,4.400000
8,JUNGLE,Belveth,1,0,1,0.000000,7.000000,10.000000,15.000000,2.200000
2,BOTTOM,Kaisa,4,2,2,0.500000,4.500000,1.750000,1.750000,3.571429
0,BOTTOM,Draven,3,2,1,0.666667,14.000000,5.000000,5.000000,3.800000
4,BOTTOM,MissFortune,3,2,1,0.666667,14.333333,5.000000,3.000000,3.466667
6,BOTTOM,Vayne,3,2,1,0.666667,9.333333,5.333333,6.333333,2.937500
1,BOTTOM,Ezreal,2,1,1,0.500000,11.000000,4.500000,6.000000,3.777778
3,BOTTOM,Lucian,1,1,0,1.000000,6.000000,6.000000,9.000000,2.500000
5,BOTTOM,Nilah,1,1,0,1.000000,3.000000,4.000000,6.000000,2.250000
7,BOTTOM,Xayah,1,1,0,1.000000,16.000000,3.000000,8.000000,8.000000

In [19]:
if 'Keria' in stats.index.get_level_values('player'):
    keria_stats = stats.loc["Keria"].reset_index().sort_values(
        ["teamPosition", "games", "winrate"], ascending=False
    )
else:
    keria_stats = pd.DataFrame()
keria_stats

,teamPosition,championName,games,win,loss,winrate,kills,deaths,assists,kda
8,UTILITY,Nautilus,4,4,0,1.0,1.75,4.25,16.75,4.352941
4,UTILITY,Alistar,2,1,1,0.5,1.00,7.50,13.50,1.933333
5,UTILITY,Gragas,1,1,0,1.0,2.00,5.00,14.00,3.200000
6,UTILITY,Heimerdinger,1,1,0,1.0,2.00,6.00,14.00,2.666667
7,UTILITY,Karma,1,0,1,0.0,4.00,7.00,8.00,1.714286
9,UTILITY,Rakan,1,0,1,0.0,0.00,8.00,17.00,2.125000
10,UTILITY,Viego,1,0,1,0.0,3.00,7.00,2.00,0.714286
1,TOP,Fiora,1,1,0,1.0,3.00,6.00,4.00,1.166667
2,TOP,Gangplank,1,0,1,0.0,3.00,11.00,8.00,1.000000
3,TOP,Gragas,1,0,1,0.0,6.00,6.00,5.00,1.833333
0,BOTTOM,Ezreal,1,1,0,1.0,6.00,5.00,8.00,2.800000